// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSdL0Ha9q1wuaacQ32_c1B_UMs3BIPXrg',
    appId: '1:960752389393:android:7d2835beb989425b80d0b0',
    messagingSenderId: '960752389393',
    projectId: 'uber-eats-bfd38',
    databaseURL: 'https://uber-eats-bfd38-default-rtdb.firebaseio.com',
    storageBucket: 'uber-eats-bfd38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQ5X_44vBt4hWHAdS6j-3hY_Yrt4Gegc',
    appId: '1:960752389393:ios:a5c747ca4153081780d0b0',
    messagingSenderId: '960752389393',
    projectId: 'uber-eats-bfd38',
    databaseURL: 'https://uber-eats-bfd38-default-rtdb.firebaseio.com',
    storageBucket: 'uber-eats-bfd38.appspot.com',
    androidClientId: '960752389393-t14q9peh58b442db57subr6sk0jq7jd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ubereatsdriver',
  );
}
